### ISSUE TITLE
getting-started-with-ubuntu - can't find kobuki files

### ISSUE THREAD

**Issue by mwwoodm** [aws-robotics/aws-robomaker-robotics-curriculum#11]
Hello!
For the second course in the RoboMaker Curriculum "getting-started-with-ubuntu" in the section MODULE 4 - BUILDING TOOLS section on "Custom ROS packages fix" there is an instruction to have the Turtlebot 2 simulation running using the command:

git clone https://github.com/turtlebot/kobuki

However, the command fails and the link on github appears to be dead. Is there another location to download the kobuki files required for the simulation?

**Comment by quattrinili** [comment]
Hi Michael,

sorry for the typo, the link is supposed to be

https://github.com/yujinrobot/kobuki

and it is fixed in the pull request. Thanks again for reporting the issue!

**Comment by mwwoodm** [comment]
Wow, that was quick. Thanks for the fix, Alberto!

**Comment by mwwoodm** [comment]
That seemed to work great. Another observation is that once the kobuki repo is cloned, the next command is:

rosdep install --from-paths src --ignore-src -r -y

But following the commands verbatim, the above command does not work from the current ~/ros_workspace/src directory but needs to be executed from one directory up, either:

cd ~/ros_workspace

or

cd ..

**Comment by quattrinili** [comment]
Hi Michael, sorry for the late reply on your followup and for the issue. 

The header file missing is not from ROS but is related to the standard library from C++. In Ubuntu, that is available in `libstdc++-7-dev` package. You can install it with 

`sudo apt install libstdc++-7-dev`

To find the package, you can search for the package containing the file from  [Ubuntu package search](https://packages.ubuntu.com/). At least in my tests with a clean system Ubuntu 18.04, that package was installed; not sure what your configuration was that did not have it already in the system. Please let me know how that goes. Thanks!

**Comment by mwwoodm** [comment]
Thank you for the reply, Alberto!
I tried that command and it seems that I did in fact have the latest libstdc++-7-dev which makes sense since I'm coming off of a clean build of Ubuntu 18.04 directly from the Ubuntu website.
I reran the colcon build command and got the same error.
Please let me know what diagnostics I can run and thank you in advance if you are able to provide further advice!
Regards,
Mike

**Comment by quattrinili** [comment]
I realized that it seems in your workspace, OpenCV appears has been included. Instead that shouldn't be cloned. 
This is what is in the test environment I have:
```
class@ubuntu:~/ros_workspace/src$ ls
CMakeLists.txt  kobuki  turtlebot  turtlebot_simulator
class@ubuntu:~/ros_workspace/src$ ls kobuki
README.markdown  kobuki.rosinstall    kobuki_bumper2pc     kobuki_controller_tutorial  kobuki_keyop  kobuki_random_walker  kobuki_safety_controller
kobuki           kobuki_auto_docking  kobuki_capabilities  kobuki_description          kobuki_node   kobuki_rapps          kobuki_testsuite
```
Note that `kobuki_desktop` is not necessary. Please double check that you have only those, which should allow for proper compilation -- I tested again with a clean installation. If you still have the error, please include also the list of folders you have in `ros_workspace/src`.

---
While out of the scope of the course, just a brief explanation of the C++ error, which seems to be related to OpenCV that for some reasons is in the workspace. Pretty much as the error shows, the header file cannot be found. Here an explanation of `#include_next` [https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html](https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html).
