### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by willysr** [aws-robotics/aws-robomaker-robotics-curriculum#2]
Hi

I tried to build the content of the repository (fundamentals-of-robotics) locally using this command: 
bundle exec jekyll build --trace --config _config.yml,_config-standalone.yml

and then i pushed the content to S3 bucket (http://fundamentals-of-robotics.s3-website-ap-southeast-1.amazonaws.com/) and set it as static web hosting.

When i click one of the link, it got broken link as the link generated is incorrect
For example
Clicking on 1. Motivation redirects to http://fundamentals-of-robotics.s3-website-ap-southeast-1.amazonaws.com/modules/0/motivation while it should be http://fundamentals-of-robotics.s3-website-ap-southeast-1.amazonaws.com/modules/0/motivation.html

Note: using bundle exec jekyll serve --trace --config _config.yml,_config-standalone.yml works fine, but it can only be used locally

**Comment by cbuscaron** [comment]
Hi @willysr,

Thank you for publishing to a static S3 site and trying it out. Just [made an update](https://github.com/aws-robotics/aws-robomaker-robotics-curriculum/commit/8d858975e50f7b39a476dcae799723de354614ed) which should fix this issue. 

Please re-sync and give it a try. Let us how it works now. 

Regards,
Cam

**Comment by willysr** [comment]
Hi @cbuscaron 

Thanks for fixing that up, but there are more broken links i found:

![image](https://user-images.githubusercontent.com/240100/99018368-78f67900-258c-11eb-87a4-df8a43b3a6a4.png)
