### ISSUE TITLE
Assessments in first course in the RoboMaker Curriculum

### ISSUE THREAD

**Issue by mwwoodm** [aws-robotics/aws-robomaker-robotics-curriculum#7]
Thank you for making this course available via GitHub! In my locally-built first course in the RoboMaker Curriculum, the end of Module 1 refers to an assessment. Are the assessments included outside of the AWS Educate program? If so, where can I find them?

**Comment by cbuscaron** [comment]
Hello @mwwoodm,

Thank you for trying the curriculum. Assessments have now been added by https://github.com/aws-robotics/aws-robomaker-robotics-curriculum/pull/8. Let us know if you find them useful. Will close this issue for now. 

Regards,
Cam

**Comment by mwwoodm** [comment]
Thank you for working on my question! I fetched the updated content from github but it looks the same to me: there is reference to an assessment but no link. I've tried running via Jekyll locally and through Docker; both pages look the same. I have Canvas and prereqs installed. Do I need to open the AWS training content in Canvas?

**Comment by quattrinili** [comment]
Hi @mwwoodm, thank you for testing it already. I made another pull request to include the links directly in the text; note however the assessment can be accessed through the menu on the right, e.g., as shown in the screenshot. Please feel free to share any other problem encountered!

<img width="1743" alt="Screen Shot 2021-01-05 at 3 52 54 PM" src="https://user-images.githubusercontent.com/5058630/103703864-52decb00-4f76-11eb-8c84-a37ed0e18acf.png">

**Comment by mwwoodm** [comment]
Yes! I see them now. I think that I did not force overwrite my local copy when I fetched the update from github. I just rm -rf my local content and cloned fresh from github and I can see the assessments now. Thank you for your help, Alberto!
